item doc correction
razorpay/razorpay-python pull request #217
Opened 2022-06-29 19:17 UTC by ankitdas13

2022-06-30 10:18 UTC, sofiya02 requested changes

2022-06-30 10:18 UTC, sofiya02 commented on documents/items.md
>  ```json
add **active** parameter

2022-06-30 19:06 UTC, ankitdas13 commented on documents/items.md
>  ```json
[done](https://github.com/razorpay/razorpay-python/blob/item_doc_correction/documents/items.md?plain=1#L60)

2022-07-01 04:06 UTC, sofiya02 approved these changes
LGTM

2022-07-01 13:24 UTC, merged